### ISSUE TITLE
Matching Bug

### ISSUE THREAD

**Issue by Orxcle-xx** [bmatcuk/doublestar#13]
Hi,

Thanks for a great library. However, it seems that I've found a bug.
```
match, _ := doublestar.Match("/@tests**", "/@tests/AppTest/TestGetCategories")
revel.ERROR.Print("Match: " + strconv.FormatBool(match))
```
This Match function returns false. I believe it matches incorrectly when first "*" in the pattern has same position as "/" in the matched string.

Best,

**Comment by bmatcuk** [comment]
Hey @Orxcle-xx! I'm glad you find my library useful! I finally had a chance to take a look at this issue and I started to work on a fix when I realized it's really working as intended. I was using bash's globstar functionality as my inspiration and it doesn't really support this syntax either: globstars/doublestars are meant to be by themselves (ie, between path separators like `/**/`). Your pattern can be rewritten as `/@tests*/**` and it should work as you intended.
