### ISSUE TITLE
path separator on Windows

### ISSUE THREAD

**Issue by stu-b-doo** [bmatcuk/doublestar#15]
I don't know how much you're trying to mimic path/filepath.Glob with this but on Windows, path/filepath.Glob converts forward slash to the appropriate path separator. 

```
fmt.Println(filepath.Glob("*/*/*.txt"))                      // rel path to my txt files
fmt.Println(doublestar.Glob("**\\*.txt"))                    // works on windows only
fmt.Println(doublestar.Glob(filepath.FromSlash("**/*.txt"))) // FromSlash conversion , should work cross platform
fmt.Println(doublestar.Glob("**/*.txt"))                     // Doesn't work on windows
```

Using filepath.FromSlash works for me in my current problem but could be useful to use this in doublestar.Glob and Match anyway?

Neat package :)

**Comment by stu-b-doo** [comment]
Unfortunately, path/filepath.FromSlash doesn't work to convert forward slash to a Windows path separator: if the pattern matches a file in the subdir, path/filepath.FromSlash resolves to the relative path for that file. 

So it seems to work if all the hits to the pattern are in a subdirectory, but if there are any files that match the pattern in the current directory, FromSlash seems to resolve the pattern to the path of that match.

**Comment by bmatcuk** [comment]
Ah, interesting... I'll see what I can come up with =) I just got back from vacation, so it might be a couple days. Thanks!

**Comment by bmatcuk** [comment]
So, sounds like `filepath.FromSlash` should fix the issue. I've made Glob call FromSlash internally. Let me know if you have any issues! =)
