### ISSUE TITLE
weird github repo http issue

### ISSUE THREAD

**Issue by solderjs** [bmatcuk/doublestar#18]
Both on Windows and CircleCI (via Docker RUN) it seems that packages that depend on this are getting empty repos rather than code. See https://github.com/UnnoTed/fileb0x/issues/50

Ubuntu and Mac OS seem unaffected.

I forked your repo and used a `replace` directive in the `go.mod` to my fork, no code changes whatsoever, and `go get` now works on Windows.

This leads me to believe that there's some sort of weird issue with the repo and Github's CDNs or some such.

I'm wondering if you could try force pushing an old commit and then updating, or deleting the v1.1.1 tag and then force updating it (to the same commit of course) or something like that that might trigger Github's caching mechanisms to bust and deliver code (and maybe just pushing a new tag to the same commit).

**Comment by bmatcuk** [comment]
That's a very strange issue... could you try running `go clean -modcache` (https://github.com/golang/go/issues/26695)?

**Comment by bmatcuk** [comment]
I see you closed the related ticket on fileb0x... should we close this issue, too?

**Comment by bmatcuk** [comment]
I'm going to close this ticket since I haven't heard from you in a while.

**Comment by solderjs** [comment]
Sorry.

I never figured out what the issue was. There was another issue dealing with hashing symlinks in go 1.11.3 or so and it’s possible that the error message was a red herring (the repo wasn’t empty, but failed checksums and was then cleaned up or error by go get or some such) and that versioned weren’t tightly locked and so the windows and docker environments had the newer, buggier version at the time.

**Comment by solderjs** [comment]
Or maybe it was that I ran `go mod vendor` on the good system, committed to the repo, and let the bad system `go build -mod vendor`.

**Comment by bmatcuk** [comment]
lol, ghost in the wires, indeed!
