### ISSUE TITLE
Globstar returning false positives

### ISSUE THREAD

**Issue by poffe** [bmatcuk/doublestar#2]
Using a globstar in glob patterns seems to return more than it should.

Adding a MatchTest of:
```go
{"**/c", "a/b", false, nil, true},
```
and running the tests gives:
```
--- FAIL: TestGlob (0.01s)
	doublestar_test.go:125: #60. Glob(`**/c`) = []string{"test/a", "test/a/b", "test/a/b/c", "test/a/b/c", "test/a/c", "test/a/c", "test/abc", "test/axbxcxdxe", "test/axbxcxdxe/xxx", "test/axbxcxdxexxx", "test/b", "test/b/c", "test/c"} - contains a/b, but shouldn't
FAIL
exit status 1
```
or have I misunderstand how globstar is supposed to work?

Best regards, Poffe.

**Comment by bmatcuk** [comment]
You're right, that's not the way that should work! I've corrected the issue and commit a fix just now.

**Comment by poffe** [comment]
Great work! Thanks for the superfast update.

**Comment by bmatcuk** [comment]
Thanks! No problem =)
