### ISSUE TITLE
🐞 There may be some bugs

### ISSUE THREAD

**Issue by storyicon** [bmatcuk/doublestar#20]
Unfortunately, I found that your `document` does not match the behavior of the `doublestar.Match()`

1. As mentioned in the document , `*` will not match any path separators, but `doublestar.Match("*", "/")` will return `true`, and golang's native `path.Match()` will return `false`.
2. `doublestar.Match("*", "")` will return `true`, which looks like `"*"` can match 0 or more characters, but `doublestar.Match("/*", "/")` returns `false`
3.  As mentioned in the documentation, `*` will not match any path separators, but `doublestar.Match("/*", "/debug/")` will return `true`.
4. `doublestar.Match("/**/profile", "/debug/pprof/profile/")` will return `true`. Although in most cases "profile" has the same meaning as "profile/", but the result is not rigorous and not intuitive.

The document of `doublestar.Match()` is so similar with the golang's native `path.Match()`, which leads me to think that you just added support for "**" and "{}", but now it seems that they return the opposite result in many cases.

I appreciate your work, maybe there is some misunderstanding in the above content, I look forward to your reply, thank you

**Comment by storyicon** [comment]
I spent some time making it work as expected. Since I haven't read your code completely, I'm not sure if these changes will import new bugs.But if you think these changes are going in the right direction, I will submit PR.

**Comment by bmatcuk** [comment]
Hmm, ya, I expect your first three points are from an optimization to return true if the last term of the pattern is `*`. If you want to submit a PR, I'll take a look at your code =)

**Comment by bmatcuk** [comment]
Hey @storyicon - thanks again for reporting the issues and submitting the PR! After digging into it, I decided a on a different approach the solve the issue. I even added some tests to make sure the output of my functions matches the output from the official golang functions they are meant to replace.

Would you mind testing real quick to make sure my changes fix all the issues you've found?

**Comment by storyicon** [comment]
😊 Sorry, I just saw it, thank you for your work, doublestar is now working very well for me.
