### ISSUE TITLE
failed to clean up git repository status output: M test/broken-symlink

### ISSUE THREAD

**Issue by bmatcuk** [bmatcuk/doublestar#22]
From @cequintana:

> I keep getting this error when I attempt to build fossa-cli. Thoughts?
> 
> Solving failure: (1) failed to clean up git repository at C:\Users\cquintana\go\pkg\dep\s ources\https---github.com-bmatcuk-doublestar - dirty? corrupted? status output: M test/broken-symlink (2) failed to list versions for ssh://git@github.com/bmatcuk/doublestar: git@github.com: Permission denied (publickey). fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. : exit status 128 (3) failed to clean up git repository at C:\Users\cquintana\go\pkg\dep\s ources\git---github.com-bmatcuk-doublestar - dirty? corrupted? status output: M test/broken-symlink (4) failed to clean up git repository at C:\Users\cquintana\go\pkg\dep\s ources\http---github.com-bmatcuk-doublestar - dirty? corrupted? status output: M test/broken-symlink

**Comment by bmatcuk** [comment]
doublestar includes some automated tests and a directory of files to run those tests on. It looks like Windows doesn't like some of the stuff in that test directory. I'll have to come up with a different solution to run those tests... I'll try to get to that this weekend.

**Comment by cequintana** [comment]
Thank you very much for your message Bob @bmatcuk Let me know when its fixed - I will test!

**Comment by bmatcuk** [comment]
@cequintana ok, I have an update available. You may need to remove the existing files for the error to go away. That means deleting `C:\Users\cquintana\go\pkg\dep\sources\https---github.com-bmatcuk-doublestar`. Could you give it a try and let me know how it goes?

**Comment by cequintana** [comment]
Hi Bob! Thank you so much for adding the fix! The error regarding the doublestar is gone.  Thats great. But I have an open issue with Fossa-cli. That project is not building. Not sure if it doesn't work on Windows . This issue can be closed! Thanks again!

**Comment by bmatcuk** [comment]
Excellent! Good luck with fossa-cli =)
