### ISSUE TITLE
Some minor deviations

### ISSUE THREAD

**Issue by storyicon** [bmatcuk/doublestar#23]
I am happy to see that the `doublestar` has been updated, but after test, the match between `/*` and `//` is `true`, which is not compatible with the statement you made in the documentation:
```
 *	matches any sequence of non-path-separators
```
The way to reproduce this mistake:
```go
Match(`/*`, `//`)
```

**Comment by bmatcuk** [comment]
What's actually happening here is that doublestar is normalizing `//` to be `/`, which, then, _does_ match the pattern `/*`. I would argue go's Match algorithm is wrong here; normalizing double path separators into a single separator is very common. For example, in bash, I can run `ls //` and get the same results as `ls /`. In fact, even crazy things like `ls /////usr////////local/////bin` work just fine. Not sure I want to "fix" this one since I think I prefer this normalization behavior. Thoughts?

**Comment by storyicon** [comment]
bmatcuk, I spent a morning evaluating the problem, because I think it really needs caution.
I use `doublestar` for `URL path matching`. As I can see, your original intention of `doublestar` is to match paths in the `file system`.
After my test, in URL path matching, neither an HTTP framework like `gin` nor `echo` treats `//about` as `/about`, but for some traditional websites, they do think of multiple `/` as one `/`.
After consideration, I have the following two points:
①I think `doublestar` can play more space, not just the matching of `file system` paths. 
②I think the `match` should be more rigorous and fit the expectations of the expression. So `doublestar` should not make any undeclared presuppositions for users (such as converting multiple `/` into one `/`). If it is necessary, I recommend using it as a switch.
This is really a corner case, which I haven't noticed before.
I am sorry that my reply is late. `doublestar` is great, thank you

**Comment by bmatcuk** [comment]
Hmm, ok, I thought about this for a little bit and I've come over to your side =) I've removed the code that ignores multiple slashes in the paths and patterns. My thinking is: if a user has problems with double slashes, they can always clean-up their input before calling doublestar. But if I leave in the code that cleans it up, then someone who wants to treat `/` differently from `//` has no option to do so.

Can you give the latest code a try?

**Comment by storyicon** [comment]
It is working very well for me now, doublestar is great, thank you

**Comment by bmatcuk** [comment]
Awesome! You're welcome!
