### ISSUE TITLE
Slash terminated pattern does not match.

### ISSUE THREAD

**Issue by makiuchi-d** [bmatcuk/doublestar#29]
The pattern `"*/"` does not match to the name `"a/"`.
This is different from standard library `path` and `path/filepath`.

https://play.golang.org/p/KNjSNRHQ7HH

```go
func main() {
	name := "a/"
	pattern := "*/"
	pResult, _ := path.Match(pattern, name)
	fpResult, _ := filepath.Match(pattern, name)
	dsResult, _ := doublestar.Match(pattern, name)
	fmt.Println(pResult, fpResult, dsResult)
}
```
 Result: `true true false`

**Comment by bmatcuk** [comment]
Thanks for the bug report... I'll take a look at this over the weekend

**Comment by bmatcuk** [comment]
I think I've fixed the issue... give it a try and let me know! Your test cases seem to pass locally, but the go playground is still failing - I suspect it's because they've cached an older version of doublestar.

**Comment by makiuchi-d** [comment]
It worked perfectly! Thank you!

**Comment by bmatcuk** [comment]
Great! Glad to help =)
