### ISSUE TITLE
Glob does not sort the results

### ISSUE THREAD

**Issue by gvre** [bmatcuk/doublestar#30]
Hello,

It seems `doublestar.Glob` does not sort the results, like `filepath.Glob` does.

Steps to reproduce:
```
$ mkdir /tmp/test && cd /tmp/test && touch {1,2,a,b}
```

```
$ cat main.go
package main

import (
        "fmt"
        "path/filepath"

        "github.com/bmatcuk/doublestar"
)

func main() {
        pattern := "*"

        fpath, _ := filepath.Glob(pattern)
        dstar, _ := doublestar.Glob(pattern)

        fmt.Println("filepath:", fpath)
        fmt.Println("doublestar:", dstar)
}
```

```
$ go run main.go
filepath:   [1 2 a b main.go]
doublestar: [2 1 a main.go b]
```

**Comment by bmatcuk** [comment]
Hmm, while compatibility with the built-in Match/Glob functions is a design goal, the documentation for Glob does not seem to guarantee sorted results. I think if it's important that the results are sorted, you should probably sort them after running Glob - even when using the native implementation, as there's no guarantee that the result will be sorted.

Thoughts?

**Comment by gvre** [comment]
Although it is not part of the exported function's documentation, [sort.Strings](https://golang.org/src/path/filepath/match.go#L324) is used to sort the results ([documented here](https://golang.org/src/path/filepath/match.go#L307)), probably because that is what people expect when glob is used. Personally, I could sort the results, but I think the library should do that, if compatibility with the built-in functions is a design goal.

Here is some extra information about globbing:
- [POSIX](https://pubs.opengroup.org/onlinepubs/007908775/xsh/glob.html)
- [Rust](https://docs.rs/glob/0.3.0/glob/fn.glob.html)

**Comment by bmatcuk** [comment]
Ok, fair enough! I've just pushed an update that should sort the results. Let me know if you run into any problems with it =)

**Comment by gvre** [comment]
That's great! Thanks a lot.

**Comment by bmatcuk** [comment]
You're welcome! =)
