### ISSUE TITLE
Feature request: `os` package abstraction

### ISSUE THREAD

**Issue by twpayne** [bmatcuk/doublestar#33]
Firstly, thank you for this great library!

I'd like to be able to use the functions in my unit tests that run in a "virtual" root filesystem that is really a temporary directory in a real filesystem. This temporary directory is created just for the test and is cleaned up after the tests are run. This means that my tests are hermetic and bugs in my code do not damage the real filesystem.

This means that the paths passed to `os.Open`, `os.Stat`, and `os.Lstat` need to be modified, for example `os.Open("/home/user/file")` needs to be translated to `os.Open("/tmp/dir/somewhere/with-random-characters/home/user/file")`.

Would you accept the PR that does the following:

* Does not touch the existing `doublestar` API.

* Adds a new function, say `GlobOS(vos OS, pattern string) ([]string, error)` that is just like the existing `Glob(pattern string) ([]string, error)` function except it takes an interface as the first parameter:

```go
type OS interface {
	Open(name string) (*os.File, error)
    Stat(name string) (os.FileInfo, error)
    Lstat(name string) (os.FileInfo, error)
    PathSeparator() rune
}
```

* Provides an `StandardOS` value that implements the above `OS` interface and calls the underlying standard library functions.

* Refactors `Glob` to be a call `GlobOS(StandardOS, pattern)`.

This would have the following benefits:

* No changes to the API for existing users.

* You run tests for Windows filesystems that run on Linux.

* Users can use `doublestar` with virtual filesystem libraries like [`go-vfs`](https://github.com/twpayne/go-vfs), [`afero`](https://github.com/spf13/afero), and [`billy`](https://github.com/src-d/go-billy).

Would you accept such a PR?

**Comment by bmatcuk** [comment]
Sounds good to me! Should make it easier to write tests for code that use doublestar. I've merged your PR =)
