### ISSUE TITLE
Add Dependabot analisys to the project 

### ISSUE THREAD

**Issue by edumco** [bmatcuk/doublestar#36]
[Dependabot](https://dependabot.com/) is a free service bought by Github that analise all dependencies listed in your project and send pull requests whenever a new version of any of these dependencies is released.

If the project has a CI the tests are automaticly trigged and the new dependency is tested wihout affect the master branch.

**Comment by bmatcuk** [comment]
doublestar has no dependencies (see https://github.com/bmatcuk/doublestar/blob/master/go.mod)
