### ISSUE TITLE
Matches files starting with .

### ISSUE THREAD

**Issue by analytically** [bmatcuk/doublestar#41]
From Glob:

"By default, file and directory names starting with . are only matched with literal .. The patterns *, **, ?, and [] will not match a leading .. To alter this behavior, you can use the DOTGLOB flag."

**Comment by bmatcuk** [comment]
This is true in bash, and perhaps some other glob implementations, but doublestar seeks to be a drop-in replacement for go's standard Match and Glob functions. In go's implementation, wildcards match files beginning with a dot.
