### ISSUE TITLE
[bug] Readdir errors reset glob results

### ISSUE THREAD

**Issue by InfiniteTF** [bmatcuk/doublestar#43]
Hi,
a change was introduced in 1.30 to return the error from readdir, but this change is causing the glob results to get corrupted due to nil getting returned and overwriting all previous glob results.

https://github.com/bmatcuk/doublestar/blob/master/doublestar.go#L452

From what I can tell the line should just `return` rather than `return nil, err`.

**Comment by bmatcuk** [comment]
Yup, I agree with that assessment! I've cut a new version of both v1 (v1.3.2) and v2 (v2.0.1) with the fix. Let me know if that solves the problem for you!

**Comment by InfiniteTF** [comment]
> Yup, I agree with that assessment! I've cut a new version of both v1 (v1.3.2) and v2 (v2.0.1) with the fix. Let me know if that solves the problem for you!

It absolutely does, thanks for the quick response!
