### ISSUE TITLE
Can't check doublestar out on Windows

### ISSUE THREAD

**Issue by cortesi** [bmatcuk/doublestar#5]
Hi there. Thanks for the a neat and well-put-together module. I have two projects that use doublestar [devd](http://github.com/cortesi/devd) and [modd](http://github.com/cortesi/modd). Both of these are cross-platform, with releases on Windows. Unfortunately the doublestar repo includes files that can't exist on Windows, which means that a "go get" of my projects won't work. Here's an excerpt:

<img width="788" alt="screen shot 2016-02-08 at 4 47 18 pm" src="https://cloud.githubusercontent.com/assets/22544/12878152/528b877e-ce84-11e5-8b73-9a85b111602f.png">

**Comment by bmatcuk** [comment]
Ok, I've removed the tests so it should work on windows. Let me know!

**Comment by cortesi** [comment]
Thanks for the quick response. That works now.
