### ISSUE TITLE
GlobOS bug when processing alternatives

### ISSUE THREAD

**Issue by pavelbazika** [bmatcuk/doublestar#50]
Hi,

there is a bug when pattern starts with alternatives. `Glob` is called recursively instead of `GlobOS`.

https://github.com/bmatcuk/doublestar/blob/33c2b222a7d1f92626a41e980c0c05f257fe70fd/doublestar.go#L308

Best regards

Pavel

**Comment by bmatcuk** [comment]
Oops! Good catch! Fixed in v2.0.4 and v1.3.4.
