### ISSUE TITLE
Support using exclamation mark (!) in non-matching character classes

### ISSUE THREAD

**Issue by sspaink** [bmatcuk/doublestar#51]
Would the maintainers of this package be comfortable with supporting the exclamation mark (!) as an alternative to the caret (^) in non-matching character classes? e.g.: `[!class]` instead of `[^class]`
Relevant issue: https://github.com/golang/go/issues/41394 

I'd be happy to make a pull request, looking at the code it looks like a straightforward change. Thank you!

**Comment by bmatcuk** [comment]
Hey @sspaink... my only qualm is that it is a breaking change as there is a (remote) possibility that someone may have included an exclamation mark in the beginning of their character class with the intention of _including_ it. I can cut a v3, though.

I'm going to grab some lunch and then I'll bang that out... pun intended =)

**Comment by bmatcuk** [comment]
Just cut v3 =)
