### ISSUE TITLE
io/fs version

### ISSUE THREAD

**Issue by cugu** [bmatcuk/doublestar#53]
Hi Bob, 

thanks for this awesome package!

I created a version for the upcoming [io/fs](https://tip.golang.org/pkg/io/fs/): https://github.com/forensicanalysis/fsdoublestar

I just wanted to let you know and say thanks.

**Comment by bmatcuk** [comment]
Do we know when io/fs might make it into a stable go release?

**Comment by cugu** [comment]
Yes, in Go 1.16, next month.

**Comment by bmatcuk** [comment]
Cool, thanks =)

**Comment by bmatcuk** [comment]
Hey @cugu: wanted to let you know, doublestar officially supports io/fs now. I just released v4 - it's a complete rewrite with much better performance and io/fs support. Check it out =)

**Comment by cugu** [comment]
Nice! I'm gonna try it. Thanks for the info!
