### ISSUE TITLE
**.go doesn't match dir/file.go

### ISSUE THREAD

**Issue by edigaryev** [bmatcuk/doublestar#54]
Documentation for `**` in [`doublestar.Match()`](https://pkg.go.dev/github.com/bmatcuk/doublestar/v3#Match) says:

```
  '**'        matches any sequence of characters, including
              path separators.
```

The comment in the matching code also seems to imply similar properties:

https://github.com/bmatcuk/doublestar/blob/ff8da227480d92566a7716286127729290c87c34/doublestar.go#L223-L225

Despite this, `doublestar.Match("**.go", "dir/file.go")` returns `false`: https://play.golang.org/p/BUl4Dsrlxlp.

**Comment by bmatcuk** [comment]
From the readme:

> A mid-pattern doublestar (**) behaves like bash's globstar option: a pattern such as path/to/**.txt would return the same results as path/to/*.txt. The pattern you're looking for is path/to/**/*.txt.
