### ISSUE TITLE
How to search relative to the current directory with io.FS version? 

### ISSUE THREAD

**Issue by maxmcd** [bmatcuk/doublestar#55]
Imagine I might be missing something obvious. If I have a file like `/a/b/c/d.go` and I want to let a process within `/a/b/c/` match on `*.go` but also on `../c/d.go` how do I do that? 

It seems if I create an fs with `os.DirFS("/a/b/c/")` I can get the first example to work, but then I can't get the second example to work since passing `../c/d.go` to the `fs.FS` created by the `os.DirFS` will error. `fs.Sub` also doesn't seem to solve this problem. 

It seems like I could get around this by providing my own fs.FS with the properties needed to move up directories, but I'm wondering if there is a suggested solution here outside of moving back to v3?

Edit: oh, do I just pre-process the input and compute the absolute path?

**Comment by maxmcd** [comment]
```go

**Comment by maxmcd** [comment]
Ok, going to close this, since the answer now seems obvious, but for clarity.

If I want a pattern like `../*.go` relative to the current directory, I do the following:
```go
input := "../*.go"
wd, _ := os.Getwd()
f := os.DirFS("/")
doublestar.Glob(f, filepath.Join(wd, input))
```

**Comment by bmatcuk** [comment]
Ya, as you discovered, that'll work. It's a limitation in io/fs, unfortunately. Another option would be to use SplitPattern() as in the example in the readme: https://github.com/bmatcuk/doublestar#splitpattern

```go
base, pattern := SplitPattern("../*.go")
// base will be ".." and pattern will be "*.go" at this point
fsys := os.DirFS(base)
matches, err := Glob(fsys, pattern)
```

I _think_ `DirFS` will accept `..` and do the right thing.

**Comment by maxmcd** [comment]
Yeah, as I was writing it I was like "oh wait is this even about this lib?", feel like I'm just getting familiar with io/fs.

Thanks for the follow-up!

**Comment by maxmcd** [comment]
I will say @bmatcuk, there is a bit of nastiness here. In my example above the `filepath.Join(wd, input)` is invalid because it starts with a preceding slash. (Your example will work as-is).

Both Glob and GlobWalk ignores IO errors on the initial call to `fs.Stat`: https://github.com/bmatcuk/doublestar/blob/f7a81184821a624c0c3a0f79eb8293457402fea8/globwalk.go#L50-L51

So in my use the invalid path silently failed and returned no results, it might be good to check for a `*PathError` here and return those errors: https://golang.org/pkg/io/fs/#PathError

**Comment by bmatcuk** [comment]
Hmm, ya, that's crap. I don't think they fully thought through everything in the io/fs package - io/fs.Glob will also silently fail, for example:

```go
	fsys := os.DirFS("/")
	files, err := fs.Glob(fsys, "/path/to/something/that/exists/*")
	if err == nil {
		for _, file := range files {
			fmt.Println(file)
		}
	} else {
		fmt.Println(err)
	}
```

Prints nothing unless you remove that starting `/` from the pattern 😢 doublestar can strive to be better, though! I'll think about how to handle this - most of the time, we do want to ignore IO errors (for example, if a directory doesn't exist), so I need to be selective about the errors that should be handled.

**Comment by maxmcd** [comment]
Found the discussion: https://github.com/golang/go/issues/44092#issuecomment-774132549

This seems like a rough part of the learning curve, not sure I understand the argument that "these are known invalid paths but we will not error on them".

**Comment by sebastien-rosset** [comment]
The proposed `SplitPattern` solution can yield unexpected results. If looking for a drop-in replacement of `filepath.Glob` with `**` support, it is tempting to write a wrapper function that takes a `pattern`. The subtle point is that in some cases `doublestar.Glob` returns an empty array whereas `filepath.Glob` returns an array of length > 0.

See https://go.dev/play/p/qSWoMWjq121

**Comment by bmatcuk** [comment]
Ya, this is actually intentional as doublestar.Glob is meant to be a drop-in replacement for io/fs.Glob, which also has this odd behavior. See the note at the bottom of doublestar.Glob's documentation: https://github.com/bmatcuk/doublestar#glob

You'll need to strip out /./ and /../ segments.

**Comment by sebastien-rosset** [comment]
ok, thanks. I'm trying to figure out how to take as input any arbitrary path provided by the user (relative, absolute, symlink...)

**Comment by sebastien-rosset** [comment]
Here is what I came up with. I'm trying to get a drop-in replacement for `filepath.Glob`, with the additional functionality that it supports double-star. It feels there ought be a simpler way.

```golang
// Glob takes the same argument as filepath.Glob, and it supports the double-star operator.
// The matching paths have the same format as what is returned by filepath.Glob
func Glob(pattern string) ([]string, error) {
	pattern = filepath.Clean(pattern)
	base, f := doublestar.SplitPattern(pattern)
	if base == "" {
		base = string(os.PathSeparator)
	}
	matches, err := doublestar.Glob(os.DirFS(base), f)
	if err != nil {
		return nil, err
	}
	for i := range matches {
		matches[i] = filepath.Join(base, matches[i])
	}
	if len(matches) == 0 {
		matches = []string{pattern}
	}
	return matches, nil
}
```

Full program at https://go.dev/play/p/d3K2PSoSfK5
