### ISSUE TITLE
Ignore subdirectories pattern

### ISSUE THREAD

**Issue by konsalex** [bmatcuk/doublestar#58]
Hey folks,

Is there any way to ignore subdirectories based on the directory name? We currently have a lerna monorepo and I find it difficult to exclude multiple `node_modules` folders, while using [addlicense](https://github.com/google/addlicense/issues/105), which mentions that is using doublestar for the file matching.

The optimal would be to use it like this
```
addlicense -c "Neo4j Inc." -f license.txt -check ./**/*.{js,ts,css} -ignore **/node_modules/*
```

but it doesn't seem to work.

The directories also are in the following tree structure

```
.
├── CONTRIBUTING.md
├── README.md
├── lerna.json
├── license.js
├── license.txt
├── node_modules
├── package.json
├── packages
│   ├── base
│   │   ├── node_modules
│   │   ├── package.json
│   │   ├── src
│   ├── html-storybook
│   │   ├── node_modules
│   │   ├── package.json
│   ├── react
│   │   ├── node_modules
│   │   ├── package.json
│   │   ├── src
│   │   └── tsconfig.json
│   └── react-storybook
│       ├── node_modules
│       ├── package.json
│       └── src
├── tsconfig.json
└── yarn.lock
```

Any clue if I am missing something?

**Comment by bmatcuk** [comment]
doublestar doesn't currently support any sort of "negative" matching, but addlicense could add support for excluding matches using the `Match()` function.

**Comment by konsalex** [comment]
Thanks for the comment @bmatcuk , have already opened an issue to their repo so let's see, feel free to close
