### ISSUE TITLE
Question: how to sponsor this project?

### ISSUE THREAD

**Issue by marcelosousa** [bmatcuk/doublestar#59]
Hi 👋 , 

Thanks so much for the work on this project! At @Reviewpad, we are trying to support the OSS projects that we use as dependencies to our main repository [reviewpad/reviewpad](https://github.com/reviewpad/reviewpad). 

Do you plan to join any sponsoring program? We are also happy to help the community to maintain the project.

Thanks!

**Comment by bmatcuk** [comment]
That's really cool! I appreciate that you're supporting your OSS dependencies!

Apparently it takes a few days to setup an account, but I'll let you know when it's ready.

Thanks again! I'm glad you're enjoying doublestar!

**Comment by bmatcuk** [comment]
Hello again @marcelosousa,

My sponsorship account has been approved: https://github.com/sponsors/bmatcuk

Thanks!

**Comment by bmatcuk** [comment]
Thanks, @marcelosousa! I appreciate that! I've added a reviewpad logo to the readme 😄 Let me know if you'd like a different logo, or would like it to point to a different url, etc.
