### ISSUE TITLE
Support for multiple nots

### ISSUE THREAD

**Issue by brodkin** [bmatcuk/doublestar#78]
I might be missing something here, but I want to be able to use the glob syntax to match all files except for those with certain file extensions.  In glob I can use the following:
```
./{app,src,resources,public}/**/*.!(css|scss)
```
As best as I can tell there is no combination of patterns accepted by this project that would allow for a series of strings in a negative match. If I have missed something I appreciate the feedback, but otherwise consider this a feature request! 😊

**Comment by bmatcuk** [comment]
doublestar does not currently support negation... it's been requested before (in #49) but I haven't had time to hack it in. Maybe I'll find some time over the holidays =)

**Comment by brodkin** [comment]
Oops, so it is! I'll close this since it duplicates #49. I'd love to see the feature added, but as opposed to #49, I am working with Talisman to scan for secrets. In this case we'd want to scan all files except those that we have deemed safe so negation is very helpful.

I appreciate your help!

**Comment by bmatcuk** [comment]
I'll try to remember to ping you when I add it =)
