### ISSUE TITLE
I want to match /xxx/xx/xx/acc.log.202302, it doesn't match /xxx/xx/xx/acc.isis.202302, should pass parameters

### ISSUE THREAD

**Issue by huozhirui** [bmatcuk/doublestar#86]
I want to match /xxx/xx/xx/acc.log.202302, it doesn't match
/xxx/xx/xx/acc.isis.202302, should pass parameters

**Comment by bmatcuk** [comment]
I'm not sure what your question is... what pattern are you trying to use?
