### ISSUE TITLE
Self-referential symlink causes issues with git and go vendoring

### ISSUE THREAD

**Issue by zaksoup** [bmatcuk/doublestar#9]
Hi, the link https://github.com/bmatcuk/doublestar/blob/master/test/abc/working-symlink references itself. I'm seeing this cause issues when copying the doublestar project into a go `vendor` directory and then attempting to add the results to git. There's some strange corner cases in that the project we're seeing this issue in is vendoring a different project which then vendors doublestar.

Here are the errors we see:
```
$ git add vendor
error: readlink("vendor/github.com/cloudfoundry/bosh-utils/vendor/github.com/bmatcuk/doublestar/test/abc/working-symlink"): Permission denied
error: unable to index file vendor/github.com/cloudfoundry/bosh-utils/vendor/github.com/bmatcuk/doublestar/test/abc/working-symlink
fatal: adding files failed
```

```
$ ll vendor/github.com/cloudfoundry/bosh-utils/vendor/github.com/bmatcuk/doublestar/test/abc/working-symlink

ls: vendor/github.com/cloudfoundry/bosh-utils/vendor/github.com/bmatcuk/doublestar/test/abc/working-symlink: Permission denied
l---------  1 pivotal  staff  15 Sep  6 15:52 vendor/github.com/cloudfoundry/bosh-utils/vendor/github.com/bmatcuk/doublestar/test/abc/working-symlink
```

You can see that it is the file which is in the vendor director of the "bosh-utils" project that is causing issues.

Please let me know if there's any more information I can provide.
Best,
Zachary Auerbach and the CF BOSH team

**Comment by bmatcuk** [comment]
I'm so sorry! I'm not sure how that happened. I've removed the errant symlink from the repo, so you should be good now.

Sorry it took so long to get to this... I've been crazy busy lately =(
