### ISSUE TITLE
Error when Pattern in {a,b,c} format

### ISSUE THREAD

**Issue by pikachuabc** [bmatcuk/doublestar#94]
Before the question really appreciate your work on this project :>

I wish to match several path expressions and from the doc [https://github.com/bmatcuk/doublestar?tab=readme-ov-file#patterns](https://github.com/bmatcuk/doublestar?tab=readme-ov-file#patterns) this lib already supports it with {a,b,c} format.

However when I tried with this pattern ```{ /logs/*-test*-*/serv/*.log*, /logs/*-test*-*/istio-proxy/*.log }``` it throws pattern error. I'm not sure where goes wrong

**Comment by ccoVeille** [comment]
Isn't the extra space?

Does this work?

`{ /logs/*-test*-*/serv/*.log*,/logs/*-test*-*/istio-proxy/*.log}`

Please provide your conf and argument if possible

**Comment by pikachuabc** [comment]
for example:

```golang
_, err = doublestar.Match("{/logs/*-test*-*/serv/*.log*,/logs/*-test*-*/istio-proxy/*.log}", "/logs/abc-test-1/serv/metrics.log")
if err != nil {
    fmt.Println(err.Error())
}
```

produce: `syntax error in pattern`

**Comment by ccoVeille** [comment]
Are you sure you are using v4?

https://goplay.space/#x-896yqH6-Z

Because it works

**Comment by pikachuabc** [comment]
ohhh... looks I was using v1.x due to wrong import... Thanks for the help!
